// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticeModule.Infrastructure;

#nullable disable

namespace PracticeModule.Infrastructure.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20250526154144_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticeModule.Domain.Entity.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("PracticeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Practice");
                });

            modelBuilder.Entity("PracticeModule.Domain.Entity.PracticeDiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("PracticeDiary");
                });

            modelBuilder.Entity("PracticeModule.Domain.Entity.StudentPracticeCharacteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("StudentPracticeCharacteristic");
                });

            modelBuilder.Entity("PracticeModule.Domain.Entity.PracticeDiary", b =>
                {
                    b.HasOne("PracticeModule.Domain.Entity.Practice", "Practice")
                        .WithMany("PracticeDiaries")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PracticeModule.Domain.Entity.StudentPracticeCharacteristic", b =>
                {
                    b.HasOne("PracticeModule.Domain.Entity.Practice", "Practice")
                        .WithMany("StudentPracticeCharacteristics")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PracticeModule.Domain.Entity.Practice", b =>
                {
                    b.Navigation("PracticeDiaries");

                    b.Navigation("StudentPracticeCharacteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
