// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelectionModule.Infrastructure;

#nullable disable

namespace SelectionModule.Infrastructure.Migrations
{
    [DbContext(typeof(SelectionDbContext))]
    [Migration("20250527182752_add comment update")]
    partial class addcommentupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.Entites.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator().HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.CandidateEntity", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("CandidateEntity");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.PositionEntity", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("PositionEntity_Description");
                        });

                    b.HasDiscriminator().HasValue("PositionEntity");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.SelectionEntity", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SelectionStatus")
                        .HasColumnType("integer");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CandidateId")
                                .HasColumnName("SelectionEntity_CandidateId");
                        });

                    b.HasDiscriminator().HasValue("SelectionEntity");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyEntity", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("PositionId");

                    b.HasDiscriminator().HasValue("VacancyEntity");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyResponseEntity", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VacancyId");

                    b.HasDiscriminator().HasValue("VacancyResponseEntity");
                });

            modelBuilder.Entity("Shared.Domain.Entites.Comment", b =>
                {
                    b.HasBaseType("Shared.Domain.Entites.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectionEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("ParentId");

                    b.HasIndex("SelectionEntityId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("Comment_UserId");
                        });

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.SelectionEntity", b =>
                {
                    b.HasOne("SelectionModule.Domain.Entites.CandidateEntity", "Candidate")
                        .WithOne("Selection")
                        .HasForeignKey("SelectionModule.Domain.Entites.SelectionEntity", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyEntity", b =>
                {
                    b.HasOne("SelectionModule.Domain.Entites.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyResponseEntity", b =>
                {
                    b.HasOne("SelectionModule.Domain.Entites.CandidateEntity", "Candidate")
                        .WithMany("Responses")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SelectionModule.Domain.Entites.VacancyEntity", "Vacancy")
                        .WithMany("Responses")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Shared.Domain.Entites.Comment", b =>
                {
                    b.HasOne("SelectionModule.Domain.Entites.VacancyResponseEntity", "Parent")
                        .WithMany("Comment")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SelectionModule.Domain.Entites.SelectionEntity", null)
                        .WithMany("Comment")
                        .HasForeignKey("SelectionEntityId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.CandidateEntity", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.SelectionEntity", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyEntity", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("SelectionModule.Domain.Entites.VacancyResponseEntity", b =>
                {
                    b.Navigation("Comment");
                });
#pragma warning restore 612, 618
        }
    }
}
