// <auto-generated />
using System;
using CompanyModule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyModule.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyModuleDbContext))]
    partial class CompanyModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyModule.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.CompanyPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyPersons");

                    b.HasDiscriminator().HasValue("CompanyPerson");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.PartnershipAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.CompanyRepresenter", b =>
                {
                    b.HasBaseType("CompanyModule.Domain.Entities.CompanyPerson");

                    b.HasDiscriminator().HasValue("CompanyRepresenter");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Curator", b =>
                {
                    b.HasBaseType("CompanyModule.Domain.Entities.CompanyPerson");

                    b.HasDiscriminator().HasValue("Curator");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("CompanyModule.Domain.Entities.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("CompanyModule.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Attachments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.CompanyPerson", b =>
                {
                    b.HasOne("CompanyModule.Domain.Entities.Company", "Company")
                        .WithMany("CompanyPersons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.PartnershipAgreement", b =>
                {
                    b.HasOne("CompanyModule.Domain.Entities.Company", "Company")
                        .WithMany("Agreements")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CompanyModule.Domain.Entities.Company", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("Appointments");

                    b.Navigation("CompanyPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
